### ISSUE TITLE
Can't not input "." and "," japanese 

### ISSUE THREAD

**Issue by thangluutitan** [BlacKCaT27/CurrencyEditText#14] opened 2016-04-01 10:46 UTC
"," can auto, but must allow input "."

**Comment by nazarcybulskij** [comment] 2016-04-08 11:57
Locale locale = new Locale("us", "JP");
mCurrencyEditText.setLocale(locale);

This  should  help   , but I not sure.  Try instead "us" to choose another language.     Сlass Locale  is final  to not be able to extends  your  

sorry for my english

**Comment by Praween** [comment] 2016-06-15 08:49
Trying to reset the value on certain condition, but unfortunately its not working .
CurrencyEditText mText;
mText.setText("")

Please let me know, how to set this value.

**Comment by BlacKCaT27** [comment] 2016-06-15 11:48
You should be able to just pass in whatever value you want to setText (cast as a string) and the formatter will take care of it. So for example:

int amount = 1000;
CurrencyEditText cet = (CurrencyEditText) findViewById(R.id.myCET);
cet.setText(amount.toString());

Make sure you're obtaining a reference to the actual view. If the example you posted is out how you're trying to do it, you're going to get a null pointer exception every time as mText hasn't been initialized.

**Comment by Praween** [comment] 2016-06-15 21:05
I have switch mode for two different tab. Whenever I switch mode, I use to clear the text as,
private CurrencyTextEdit mAddValue;
mAddValue = = (CurrencyTextEdit)findViewById(R.id.add_value);
......
switchMode(int mode) {
         mAddValue.requestFocus();
        mAddValue.setText("");
........
 }

I am not able to get any success with any EditText call to clear the text such as , mAddValue.getText().clear() OR mAddValue.setText(""). I tried with to put this work under runnable to execute in separate thread as well, but no success.

**Comment by BlacKCaT27** [comment] 2017-07-09 06:37
Closing this as the outstanding issue of setting an empty value to reset the view is a duplicate of issue #24

**Closed by BlacKCaT27** 2017-07-09 06:37 UTC
